# account-service.properties
server.port=8081
spring.application.name=account-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=health,info

loan.default-balance=15000
