server:
  port: 9090

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo
      client:
        registration:
          gateway:
            client-id: gateway-client
            client-secret: gateway-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
        provider:
          gateway:
            issuer-uri: http://localhost:8080/realms/demo

  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
          filters:
            - TokenRelay

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - TokenRelay

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
